services:
  database:
    image: postgres:17-alpine
    container_name: envocc-services-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=envocc_services
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data: